### ISSUE TITLE
Angular 4 {}

### ISSUE THREAD

**Issue by ranouf** [RicoSuter/NSwag#862] opened 2017-07-31 19:10 UTC
Hi,

Angular Version: "@angular/core": "^4.3.2",

I just passed to Angular 4 and I have many error with the file generated par NSwag like this one:
 ERROR in [at-loader] ./ClientApp/app/services/app.services.ts:53:9
        TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<UserDto>'.
      Type '{}' is not assignable to type 'UserDto'.
        Property 'id' is missing in type '{}'.

I tried to look for type script client tab if there is Angular version 4, but there is only 1.8and 2.0. Maybe there is way to configure the app to specify a specific way to instanciate a variable?

 ```
authenticate(id: string | undefined): Observable<UserDto | null> {
        let url_ = this.baseUrl + "/api/v1/Authentication/Authenticate?";
        if (id === undefined)
            throw new Error("The parameter 'id' must be defined.");
        else
            url_ += "id=" + encodeURIComponent("" + id) + "&"; 
        url_ = url_.replace(/[?&]$/, "");

        let options_ = {
            method: "put",
            headers: new Headers({
                "Content-Type": "application/json", 
                "Accept": "application/json"
            })
        };

       [L53] return Observable.fromPromise(this.transformOptions(options_)).flatMap(transformedOptions_ => {
            return this.http.request(url_, transformedOptions_);
        }).flatMap((response_) => {
            return this.transformResult(url_, response_, (r) => this.processAuthenticate(r));
        }).catch((response_: any) => {
            if (response_ instanceof Response) {
                try {
                    return this.transformResult(url_, response_, (r) => this.processAuthenticate(r));
                } catch (e) {
                    return <Observable<UserDto>><any>Observable.throw(e);
                }
            } else
                return <Observable<UserDto>><any>Observable.throw(response_);
        });
    }
```

Thanks
Ps: I use your app nearly every day, it works very well :)

**Comment by RSuter** [comment] 2017-08-01 17:44
This is strange. I also use nswag in an angular 4 app and it works without problems... Maybe a problem with transformOptions()?

**Comment by RSuter** [comment] 2017-08-01 17:57
I think it is a problem with transformResult() which must be defined with a generic response type so that the observable has the correct type.. will check this and either update the docs or fix the problem.

**Comment by ranouf** [comment] 2017-08-01 18:22
I can send you my nswag config, if you need.

Currently i have both (transformOptions and transformResult) checked.

I came back to the previous working version : "@angular/core": "^4.2.0", nswag is working super well.

let me now when it will be fixed :)

Thank you for your work!

**Comment by RSuter** [comment] 2017-08-03 17:15
I've upgraded the sample application to Angular 4.3.3 and this works for me without problems (or better: without your problems :-). Can you compare the projects?

**Comment by ranouf** [comment] 2017-08-03 18:12
this is my config file.
Do you need something else?

```
{
  "swaggerGenerator": {
    "webApiToSwagger": {
      "assemblyPaths": [
        "../MyProjectBackend.Api/bin/Debug/netcoreapp1.1/MyProjectBackend.Api.dll"
      ],
      "referencePaths": [
        "C:/Program Files/dotnet/shared/Microsoft.NETCore.App/1.1.1",
        "bin/Release/PublishOutput"
      ],
      "isAspNetCore": true,
      "controllerNames": [
        "MyProjectBackend.Api.Controllers.Authentication.AuthenticationController",
        "MyProjectBackend.Api.Controllers.Offers.OfferController",
        "MyProjectBackend.Api.Controllers.Places.PlaceController",
        "MyProjectBackend.Api.Controllers.Shops.ShopCategoryController",
        "MyProjectBackend.Api.Controllers.Shops.ShopChainController",
        "MyProjectBackend.Api.Controllers.Shops.ShopController",
        "MyProjectBackend.Api.Controllers.Shops.ShopLocationController",
        "MyProjectBackend.Api.Controllers.SocialAccounts.SocialAccountController",
        "MyProjectBackend.Api.Controllers.Users.UserController",
        "MyProjectBackend.Api.Controllers.Offers.ShopOfferController"
      ],
      "defaultUrlTemplate": "api/{controller}/{action}/{id}",
      "defaultPropertyNameHandling": "CamelCase",
      "defaultEnumHandling": "Integer",
      "flattenInheritanceHierarchy": false,
      "generateKnownTypes": true,
      "generateXmlObjects": false,
      "addMissingPathParameters": false,
      "infoTitle": "MyProject Web API Swagger specification",
      "infoVersion": "1.0.0",
      "output": null
    }
  },
  "codeGenerators": {
    "swaggerToTypeScriptClient": {
      "className": "{controller}Service",
      "moduleName": "",
      "namespace": "",
      "typeScriptVersion": 2.0,
      "template": "Angular",
      "promiseType": "Promise",
      "dateTimeType": "Date",
      "nullValue": "Undefined",
      "generateClientClasses": true,
      "generateClientInterfaces": false,
      "generateOptionalParameters": false,
      "wrapDtoExceptions": false,
      "clientBaseClass": "ServiceBase",
      "configurationClass": "",
      "useTransformOptionsMethod": true,
      "useTransformResultMethod": true,
      "generateDtoTypes": true,
      "operationGenerationMode": "MultipleClientsFromOperationId",
      "markOptionalProperties": true,
      "generateCloneMethod": false,
      "typeStyle": "Interface",
      "extendedClasses": [],
      "extensionCode": "ClientApp/app/services/app.services.extension.ts",
      "generateDefaultValues": true,
      "excludedTypeNames": [],
      "handleReferences": false,
      "generateConstructorInterface": true,
      "importRequiredTypes": true,
      "baseUrlTokenName": "API_BASE_URL",
      "output": "ClientApp/app/services/app.services.ts"
    }
  }
}
```

**Comment by RSuter** [comment] 2017-08-03 19:13
I think its a problem with your project setup. Can you create a sample project where this can be reproduced?

**Comment by Farshidgolkarihagh** [comment] 2017-08-04 10:25
I am using Angular 4 as well and it seems to be fine. I created an endpoint on my web api endpoint to generate the nswag code. Need to disable it when it goes on production (or add authentication to it)

    [SwaggerIgnore]
    [Route("api/[controller]")]
    public class SwaggerController : Controller
    {
        [HttpGet]
        public string Swagger()
        {
            var controllers = from t in Assembly.GetEntryAssembly().GetTypes()
                    where t.Name.Contains("Controller")
                    select t;

            var settings = new WebApiToSwaggerGeneratorSettings
            {
                DefaultUrlTemplate = "api/{controller}/{action}/{id}",
                DefaultPropertyNameHandling = NJsonSchema.PropertyNameHandling.CamelCase
            };
            var generator = new WebApiToSwaggerGenerator(settings);
            var document = Task.Run(async () => await generator.GenerateForControllersAsync(controllers.ToArray()))
                .GetAwaiter().GetResult();
            var codeSettings = new SwaggerToTypeScriptClientGeneratorSettings()
            {
                ClassName = "{controller}Client",
                GenerateClientInterfaces = true,
                Template = TypeScriptTemplate.Angular,
                UseTransformOptionsMethod = true,
                UseTransformResultMethod = false,
                ClientBaseClass = "ClientBase"
            };
            var codeGenerator = new SwaggerToTypeScriptClientGenerator(document, codeSettings);
            var retVal = codeGenerator.GenerateFile();
            return retVal;
        }
    }

**Comment by RSuter** [comment] 2017-08-04 10:29
@Farshidgolkarihagh thanks for your check. 

Just FYI: You can also use the NSwag middlewares (app.UseSwaggerUI()) to generate the spec and serve a UI (and enable it only in dev mode)

https://github.com/RSuter/NSwag/blob/master/src/NSwag.Sample.NetCoreAngular/Startup.cs#L52

**Comment by Farshidgolkarihagh** [comment] 2017-08-04 11:45
Thanks for pointing that out. it is certainly very useful for invoking the endpoints and generating the spec file.

**Comment by RSuter** [comment] 2017-08-10 21:32
Please provide a sample project to reproduce this

**Comment by RicoSuter** [comment] 2020-09-16 17:50
Closing as outdated.

**Closed by RicoSuter** 2020-09-16 17:50 UTC
Labels: state: await-repro, type: question
