### ISSUE TITLE
In the generated client code, consider desserializing from stream instead of string

### ISSUE THREAD

**Issue by paulomorgado** [RicoSuter/NSwag#542] opened 2017-01-27 09:27 UTC
The HTTP content is held by the `HttpClient` on a memory stream.

Deserializing JSON from a string instead of a stream means decoding the stream to a string only for `JsonConvert` wrapping it with a `StringReader`.

Instead of this:

```
var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
result_ = Newtonsoft.Json.JsonConvert.DeserializeObject<ResponseStatus>(responseData_);
```

Consider using something like this:

```
using (var jr = new JsonTextReader(new StreamReader(await response_.Content.ReadAsSteamAsync().ConfigureAwait(false), Encoding.UTF8)))
{
    result_ = JsonSerializer.CreateDefault().Deserialize<T>(jr);
}
```

**Comment by juanperezADD** [comment] 2019-02-21 10:21
We are also interested in this functionality.

Any idea of when it will be implemented / released?

Kind Regards

**Comment by RSuter** [comment] 2019-02-22 06:54
Duplicate of https://github.com/RSuter/NSwag/issues/1666 ?

**Closed** 2020-12-31 12:53 UTC
Labels: type: enhancement
