### ISSUE TITLE
Missing cast handling for oneOf listed schemas for response type

### ISSUE THREAD

**Issue by dinobal** [RicoSuter/NSwag#3425] opened 2021-04-20 16:04 UTC
Example generated using `NSwagStudio v13.10.9.0`

Given this openAPI specification example bellow ...
```yaml
openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /pets:
    post:
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Cat'
                - $ref: '#/components/schemas/Dog'
                - $ref: '#/components/schemas/Bird'
              discriminator:
                propertyName: pet_type
                mapping:
                  obj1: '#/components/schemas/Cat'
                  obj2: '#/components/schemas/Dog'
                  obj3: '#/components/schemas/Bird'
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Cat'
                  - $ref: '#/components/schemas/Dog'
                  - $ref: '#/components/schemas/Bird'
                discriminator:
                  propertyName: pet_type
                  mapping:
                    obj1: '#/components/schemas/Cat'
                    obj2: '#/components/schemas/Dog'
                    obj3: '#/components/schemas/Bird'
components:
  schemas:
    Pet:
      type: object
      required:
        - pet_type
      properties:
        pet_type:
          type: string
      discriminator:
        propertyName: pet_type
    Dog:
      type: object
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
      properties:
        bark:
          type: boolean
        breed:
          type: string
          enum: [Dingo, Husky, Retriever, Shepherd]
    Cat:
      type: object
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
      properties:
        hunts:
          type: boolean
        age:
          type: integer
    Bird:
      type: object
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
      properties:
        flies:
          type: boolean
        numOfTricks:
          type: integer
```
Generated client code
```typescript
export class Client {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : <any>window;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "http://api.example.com/v1";
    }

    /**
     * @param body (optional) 
     * @return Created
     */
    pets(body: Cat | Dog | Bird | undefined): Promise<Cat> {
        let url_ = this.baseUrl + "/pets";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ = <RequestInit>{
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPets(_response);
        });
    }

    protected processPets(response: Response): Promise<Cat> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = Cat.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Cat>(<any>null);
    }
}

```
I was expecting to see an union type returned and correct type cast performed but its only the first type in the `oneOf` collection of schemas? Or is it open API spec issue? How can I do this the right way....

We could maybe have something like this inside the process function?
` let resultData200 = oneOfMap200.get(resultData200[discriminatorName]).fromJS(resultData200);`

**Comment by jeremyVignelles** [comment] 2021-04-20 16:50
duplicate of https://github.com/RicoSuter/NSwag/issues/3388 ?

**Comment by dinobal** [comment] 2021-04-21 08:30
@jeremyVignelles 
Oh sorry, seems like it. Should we just close it then?

**Closed** 2021-04-21 09:07 UTC
