### ISSUE TITLE
Nswag 14: Url generation replace for parameters is now append

### ISSUE THREAD

**Issue by tommyka** [RicoSuter/NSwag#4740] opened 2024-01-30 11:19 UTC
Endpoints with parameters in the URL are not working in nswag 14.

In the client generated for v 13.2 the code was as following
![image](https://github.com/RicoSuter/NSwag/assets/1578869/f2a19e42-2b44-469f-913d-85ed19ab402f)

but in v 14.0.2 its 
![image](https://github.com/RicoSuter/NSwag/assets/1578869/abe564b2-5da2-47bf-b9d3-31620503ef23)

now the url still includes the {url} in the text, and the endpoints don't match up.

**Comment by RicoSuter** [comment] 2024-02-02 21:10
@paulomorgado could this be a regression of the optimization? Can you have a look?

**Comment by RicoSuter** [comment] 2024-02-02 21:46
Seems to be a regression of https://github.com/RicoSuter/NSwag/pull/4579

**Comment by tommyka** [comment] 2024-02-02 21:54
Vi found it was related to using a custom class template that that was created from the v13 templates.

Vi have used the v14 template and migrated our changes over, and its now fixed.

**Comment by RicoSuter** [comment] 2024-02-02 22:12
https://github.com/RicoSuter/NSwag/pull/4755

**Comment by RicoSuter** [comment] 2024-02-02 22:13
hmm...

**Comment by RicoSuter** [comment] 2024-02-02 22:55
Ok can we close the issue then?

**Closed** 2024-02-03 09:07 UTC
