### ISSUE TITLE
.NET 5 Source Generator support

### ISSUE THREAD

**Issue by fabionaspolini** [RicoSuter/NSwag#3489] opened 2021-05-31 11:38 UTC
Hi,
Is there a plan to implement .NET 5 Source Generator support?

**Comment by jeremyVignelles** [comment] 2021-05-31 12:01
Closing as duplicate of #3089

**Closed by jeremyVignelles** 2021-05-31 12:01 UTC

**Comment by HavenDV** [comment] 2021-06-16 10:54
Unofficial generator: https://www.nuget.org/packages/H.NSwag.Generator/
