### ISSUE TITLE
[Regression] Swagger.json not generated after upgrade to 13.11.x in docker container

### ISSUE THREAD

**Issue by sloncho** [RicoSuter/NSwag#3496] opened 2021-06-02 19:33 UTC
Hitting localhost:5000 when running locally (tried in windows, linux and macos) produces the proper output, but if packed in a docker container, it hangs on getting the swagger.json file. The sample works OK if using nswag 13.10.9. Not working w/ any of the 13.11.x.

It appears the problem is related to using an external (from nuget) class for a property type of the generated model. In the example we use nswag class, but we observed it with our own external assemblies.

test.csproj:
``` xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>Net5.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NSwag.AspNetCore" Version="13.11.2" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Dockerfile">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
```
Program.cs:
``` csharp
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace Test
{
    [ApiController]
    [Route("/")]
    public class Program
    {
        [NonAction]
        public static async System.Threading.Tasks.Task Main(string[] args) => 
            await Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(a =>
            {
                a.UseStartup<Program>();
                a.UseUrls(string.Empty);
                a.UseKestrel(o => o.ListenAnyIP(5000));
            })
        .RunConsoleAsync();

        [NonAction]
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseRouting();
            app.UseOpenApi();
            app.UseSwaggerUi3();
            app.UseEndpoints(o => o.MapControllers());
        }

        [NonAction]
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            services.AddOpenApiDocument();
            services.AddMvcCore();
        }

        [HttpGet("{id}")]
        public TestDetail Get()
        {
            return new TestDetail();
        }

        public sealed class TestDetail
        {
            /// <summary>
            /// NSwag 13.11.x fails to generate the swagger.json when a reference to a type in another assembly is present in the model.
            /// This only occurs when hosting in a linux docker container.
            /// No issues when running locally or in Windows docker container.
            /// </summary>
            public NSwag.OpenApiContact Test { get; set; }

        }
    }
}
```

Dockerfile:
``` dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:5.0
EXPOSE 5000
COPY . .
ENTRYPOINT ["dotnet", "test.dll"]
```

**Comment by MortenStarck** [comment] 2021-06-15 08:33
I know this is not a solution, 
But i found that since the release of dotnet 5.0.300 it stoped working. By changing it to something like this:
`FROM mcr.microsoft.com/dotnet/sdk:5.0.200-buster-slim AS build 
WORKDIR /app 
COPY Nuget.Config ./ 
COPY ./src/ ./ 
RUN dotnet restore --configfile Nuget.Config --ignore-failed-sources 
RUN dotnet build -c Release -o out  
RUN dotnet publish -c Release -o out 
FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim  
COPY --from=build /app/out . 
ENTRYPOINT ["dotnet", "API.dll"]`
It works.

**Comment by RicoSuter** [comment] 2021-06-15 09:50
I have the feeling it's about the clean up of targets etc: 
https://github.com/RicoSuter/NSwag/pull/3417

**Comment by MortenStarck** [comment] 2021-06-21 11:20
@RicoSuter can you put some more words to it. 
In my code i have configured it like so: 
`<Target Name="GenerateSwaggerJson">
        <Exec Command="$(NSwagExe_Net50) aspnetcore2openapi /project:../API/API.csproj /documentName:v1 /output:$(OutDir)swagger.json" />
    </Target>

    <Target Name="GenerateNSwagClient" DependsOnTargets="GenerateSwaggerJson">
        <PropertyGroup>
            <GeneratedSwaggerClientFile Condition="'$(GeneratedSwaggerClientFile)' ==''">$(IntermediateOutputPath)$(MSBuildProjectName).BaseClient.cs</GeneratedSwaggerClientFile>
        </PropertyGroup>
        <Copy SourceFiles="@(ReferencePath)" DestinationFolder="$(OutDir)References" />
        <Exec Command="$(NSwagExe_Net50) run nswag.json /runtime:Net50 /variables:InputSwagger=$(OutDir)swagger.json,ClientNamespace=$(RootNamespace),GeneratedSwaggerClientFile=$(GeneratedSwaggerClientFile)" />
        <RemoveDir Directories="$(OutDir)References" />
    </Target>

    <Target Name="IncludeNSwagClient" BeforeTargets="CoreCompile" DependsOnTargets="GenerateNSwagClient">
        <ItemGroup Condition="Exists('$(GeneratedSwaggerClientFile)')">
            <Compile Include="$(GeneratedSwaggerClientFile)" />
            <FileWrites Include="$(GeneratedSwaggerClientFile)" />
        </ItemGroup>
    </Target>`
And in the Nswag.json i also only have configured Runtime to "Net50". I'm also only seeing this when building the docker file, with the latest dotnet 5.0.300+ docker image.

**Comment by sloncho** [comment] 2021-11-12 14:05
Any news about this? Or what parts of the code I should look at, if I'm to try to contribute? It have been a long time, and it is still failing to this day.

**Comment by RicoSuter** [comment] 2021-11-15 17:57
Is this still a problem with nswag v13.14.4?

**Comment by sloncho** [comment] 2021-11-16 13:35
> Is this still a problem with nswag v13.14.4?

It is still not working - same repro steps.

**Comment by MortenStarck** [comment] 2021-11-16 13:52
I found it to work after i got the latest dotnet 5.0.400 and the latest Nswag version. 
But then ran into a masive memory leak in NSwag(Like it went from 500mb ram to 30GB ram use in 10 min)

**Comment by sloncho** [comment] 2021-11-16 14:59
> I found it to work after i got the latest dotnet 5.0.400 and the latest Nswag version. But then ran into a masive memory leak in NSwag(Like it went from 500mb ram to 30GB ram use in 10 min)

Can you validate w/ the original proj/docker file from this issue? I upgraded to latest nswag version, and the same docker file as above (supposedly it should be picking the latest 5.0.x), and it still fails for me.

**Comment by sloncho** [comment] 2022-01-31 20:21
I still see this problem with v. 13.15.5. Ant idea how to more diagnose this? It is serious impediment for upgrading.

**Comment by Karnich** [comment] 2022-02-15 11:08
@RicoSuter 
Ive tried using your NSwag.Sample.NET60 to see if i could replicate what we are seeing. And the same issue ocurs in that sample when using the following Dockerfile and trying to access swagger on localhost/swagger

like @MortenStarck  mentions, memory keeps increasing while it keeps trying to load the swagger file.

```
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

COPY Nuget.Config ./
COPY ./ ./

RUN dotnet restore --configfile Nuget.Config --ignore-failed-sources

RUN dotnet build -c Release -o out 

FROM mcr.microsoft.com/dotnet/aspnet:6.0
COPY --from=build /app/out .

ENTRYPOINT ["dotnet", "NSwag.Sample.NET60.dll"]
```

do anyone have a working sample using NSwag and Docker using .NET 6?
Upgrading to .NET 6 means we can no longer use the NSwag version that still works when using docker (13.10.9)

**Comment by terryjbutler** [comment] 2022-03-22 09:23
I'm also having a similar issue but in a Kubernetes cluster. Memory usage balloons until the pod is evicted when accessing the generated swagger.json. Has anybody been able to learn anything new around this issue?

**Comment by laya-alsh** [comment] 2022-08-04 09:39
Also having same problem. Updating to `.net7-preview-6` didn't help..

**Comment by lahma** [comment] 2022-08-04 14:42
Lot of different example files here. Is there any solid repro to run and what are the steps to see the OOM issue? Please explain like I'm five year old, like what besides docker build and run.

**Comment by sloncho** [comment] 2022-08-04 15:45
@lahma This issue got hijacked. The original was about not being able to generate swagger at all if classes/models from referenced assemblies are used. This is still an issue.

Then someone added the OOM issue. I think this has to be a separate issue, as people get confused, and most probably the 2 issues are not related at all.

If you do the original docker thing, it'll expose the original problem.

Btw - we solved the problem for ourselves by dropping the nswag all together and migrated to swash. This was showstopper for us.

**Comment by laya-alsh** [comment] 2022-08-05 11:55
@lahma i've played around a little bit in order to reproduce the problem.
It looks like as soon as there is any model in the schema, the NSwag starts to struggle.
I made another simple example:

`program.cs`:
```
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddOpenApiDocument();

var app = builder.Build();

app.MapGet("/", () => new SomeModel()); // <- this makes NSwag not responding..
// app.MapGet("/", () => "Hello World"); // <- this works without any issues..

app.UseOpenApi();
app.UseSwaggerUi3();

app.Run();

public class SomeModel
{
    public string Example { get; set; } = "Hello world";
}
```

`Dockerfile`:
```
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build
COPY . /app
WORKDIR /app
RUN dotnet restore
RUN dotnet publish -c Release -o publish

FROM mcr.microsoft.com/dotnet/aspnet:6.0
COPY --from=build /app/publish .
EXPOSE 80
ENTRYPOINT ["dotnet", "nswag-bug.dll"]
```

Schema (from local run):
```
{
  "x-generator": "NSwag v13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v9.0.0.0))",
  "openapi": "3.0.0",
  "info": {
    "title": "My Title",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:5000"
    }
  ],
  "paths": {
    "/": {
      "get": {
        "operationId": "Get",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SomeModel"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "SomeModel": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "example": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

Steps to reproduce:
- start project locally (VS or VS Code), navigate to `localhost:5000/swagger/v1/swagger.json` -> should work fine.
- from dockerfile location run in terminal
  - `docker build -t nswag-bug .`
  - `docker run -d -p 5000:80 nswag-bug`
- navigate again to that swagger link. It should not respond and docker will go crazy (it will not stop till it eats the whole RAM):
![image](https://user-images.githubusercontent.com/110024370/183072281-cead360f-35d6-411e-9fe6-df0c5e5a13fd.png)


I've attached the .net project (it's just 4 small files)
[nswag-bug.zip](https://github.com/RicoSuter/NSwag/files/9268299/nswag-bug.zip)

**Comment by lahma** [comment] 2022-08-05 13:10
@laya-alsh something goes terribly wrong when resolving external XML documentation. Following allows the generation to complete:

```csharp
builder.Services.AddOpenApiDocument(options =>
{
	options.UseXmlDocumentation = false;
	options.ResolveExternalXmlDocumentation = false;
});
```

@sloncho too late for you I guess, but I think you might have been experiencing the same thing.

**Comment by laya-alsh** [comment] 2022-08-05 13:20
Wow..you gave me a solution within one hour.. kudos to you! :beers:  :pray:

i confirm, that setting this solves the issue:
```
options.ResolveExternalXmlDocumentation = false;
```

**Comment by lahma** [comment] 2022-08-05 13:22
OK I think what is happening here. Because the app is in the root folder `/` and there's a kind of a bug in Namotion.Reflection which is responsible for trying to find the external XML docs. The logic will make it try to find specific file pattern from program directory *and all sub-directories*, the container basically crashes because every single file inside the container will be searched.

Another workaround is to have the compiled binaries in separate folder like ´/app´ (which would be a good idea anyway).

**Closed** 2022-08-15 11:36 UTC
