### ISSUE TITLE
Generated C# client throws API Exception on HTTP 204

### ISSUE THREAD

**Issue by dhilgarth** [RicoSuter/NSwag#2499] opened 2019-11-01 15:49 UTC
The generated method looks like this:

```
    public async Task<object> AssignNewNotifications2UsersAsync(
      DateTimeOffset since,
      CancellationToken cancellationToken)
    {
      StringBuilder stringBuilder1 = new StringBuilder();
      StringBuilder stringBuilder2 = stringBuilder1;
      string str1;
      if (this.BaseUrl == null)
        str1 = "";
      else
        str1 = this.BaseUrl.TrimEnd('/');
      stringBuilder2.Append(str1).Append("/api/notifications/assignNew?");
      stringBuilder1.Append(Uri.EscapeDataString(nameof (since)) + "=").Append(Uri.EscapeDataString(since.ToString("s", (IFormatProvider) CultureInfo.InvariantCulture))).Append("&");
      --stringBuilder1.Length;
      HttpClient httpClient = this._httpClient;
      using (HttpRequestMessage request_ = new HttpRequestMessage())
      {
        request_.Content = (HttpContent) new StringContent(string.Empty, Encoding.UTF8, "application/json");
        request_.Method = new HttpMethod("POST");
        request_.Headers.Accept.Add(MediaTypeWithQualityHeaderValue.Parse("application/json"));
        request_.RequestUri = new Uri(stringBuilder1.ToString(), UriKind.RelativeOrAbsolute);
        HttpResponseMessage response_ = await httpClient.SendAsync(request_, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        try
        {
          Dictionary<string, IEnumerable<string>> headers_ = response_.Headers.ToDictionary<KeyValuePair<string, IEnumerable<string>>, string, IEnumerable<string>>((Func<KeyValuePair<string, IEnumerable<string>>, string>) (h_ => h_.Key), (Func<KeyValuePair<string, IEnumerable<string>>, IEnumerable<string>>) (h_ => h_.Value));
          if (response_.Content != null && response_.Content.Headers != null)
          {
            foreach (KeyValuePair<string, IEnumerable<string>> header in (HttpHeaders) response_.Content.Headers)
              headers_[header.Key] = header.Value;
          }
          string str2 = ((int) response_.StatusCode).ToString();
          if (str2 == "200")
            return (await this.ReadObjectResponseAsync<object>(response_, (IReadOnlyDictionary<string, IEnumerable<string>>) headers_).ConfigureAwait(false)).Object;
          if (str2 == "204")
          {
            string response;
            if (response_.Content == null)
              response = (string) null;
            else
              response = await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
            throw new ApiException("Success", (int) response_.StatusCode, response, (IReadOnlyDictionary<string, IEnumerable<string>>) headers_, (Exception) null);
          }
          if (str2 != "200" && str2 != "204")
          {
            string response;
            if (response_.Content == null)
              response = (string) null;
            else
              response = await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
            throw new ApiException("The HTTP status code of the response was not expected (" + (object) (int) response_.StatusCode + ").", (int) response_.StatusCode, response, (IReadOnlyDictionary<string, IEnumerable<string>>) headers_, (Exception) null);
          }
          return (object) null;
        }
        finally
        {
          response_?.Dispose();
        }
      }
    }
```

Code is decorated with `[GeneratedCode("NSwag", "13.0.6.0 (NJsonSchema v10.0.23.0 (Newtonsoft.Json v11.0.0.0))")]`

The corresponding swagger.json part looks like this:

```"/api/notifications/assignNew":{
   "post":{
      "tags":[
         "Notifications"
      ],
      "operationId":"Notifications_AssignNewNotifications2Users",
      "consumes":[

      ],
      "produces":[
         "application/json",
         "text/json",
         "application/xml",
         "text/xml"
      ],
      "parameters":[
         {
            "name":"since",
            "in":"query",
            "required":true,
            "type":"string",
            "format":"date-time"
         }
      ],
      "responses":{
         "200":{
            "description":"OK",
            "schema":{
               "type":"object"
            }
         },
         "204":{
            "description":"Success"
         }
      },
      "security":[
         {
            "oauth2":[

            ]
         }
      ]
   }
},
```

**Comment by RicoSuter** [comment] 2019-11-04 15:06
I'd say this is currently by design.

Solution/duplicate: #1259

**Comment by clemensv** [comment] 2021-02-04 08:52
This issue is obviously fairly old, but I'd like to +1 it nevertheless.

```
if (status_ == 204)
{
         string responseText_ = ( response_.Content == null ) ? string.Empty : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
         throw new ApiException("Successful operation", status_, responseText_, headers_, null);
}
``` 

I understand that this is a design decision, @RicoSuter, but I don't think that decision makes semantic sense. I believe that's very apparent by just looking at what the API designer of my case here wrote for the declared 204 code: "successful operation". They simply have no entity body to return.

If you have a successful operation, don't throw. 2xx ought never be reason to create an exception, especially if declared in the contract. Throwing means that the runtime needs to capture a stack trace and then do a long jump past the call stack to find a handler. That is incredibly an expensive operation and should never happen during an expected call path. In the core messaging runtimes in Azure, we are working hard to get each and every exception off the call path that does not reflect a true exceptional situation. 204, especially if declared in the contract, is not exceptional. 

It would be great if there was a switch to enable returning an empty/null result.

That all said: You are doing absolutely fantastic work with this project. Thank you!

**Comment by jeremyVignelles** [comment] 2021-02-04 09:09
#1259 is about merging success status code, allowing null in cases of a 204. This is something I wanted to implement, but was never able to do so, because it induces a refactoring of how the library works internally.
I've written about the plans [here](https://github.com/RicoSuter/NSwag/issues/2995#issuecomment-675746287), explaining the situation.
Any PR is welcome.
I'm closing this as duplicate of #1259

**Closed by jeremyVignelles** 2021-02-04 09:09 UTC
Labels: duplicate
