### ISSUE TITLE
Can't return correct code in case of 204 returned by the API

### ISSUE THREAD

**Issue by steppo83** [RicoSuter/NSwag#3038] opened 2020-09-07 19:19 UTC
We have upgraded to the last versione (13.7) and we saw a serious bug: in case that the api returns 204 (No Content) the file generated by nSwagStudio 13.7 will return an ApiException.

This was the code with the 13.6.2 version
![image](https://user-images.githubusercontent.com/19529745/92413286-aae3fd00-f14f-11ea-8bdd-f66e8e8bc566.png)

This is the actual code with the 13.7 version:
![image](https://user-images.githubusercontent.com/19529745/92413315-c222ea80-f14f-11ea-9af2-90868b64caf5.png)

So without the check on the 204 code in case of 204 returned by the api the method will return an ApiException.

**Comment by jeremyVignelles** [comment] 2020-09-07 21:34
Hi,

This is a duplicate of #2995 and other linked bugs.

I recognize that I have made a PR with a breaking change in 13.7, but after talking with Rico, it appears to us that the new behavior is actually correct. Please [read more in this very detailed answer](https://github.com/RicoSuter/NSwag/issues/2995#issuecomment-675746287)

The short form is this:
Do you have any good reason to return both a 200 and a 204 ?
- Yes : Please tell us why?
- No, I only ever return 204 : Then, you must declare the 204 response manually in your server code. We currently don't know why ASP.net's API Explorer doesn't detect a 204, but the fact is that it doesn't, so you have to tell it.  NSwag is consistent with what is returned by APIExplorer.

Documenting every entry point could be cumbersome, so we're planning to create a ready-to-use document processor that would help with that.

**Comment by steppo83** [comment] 2020-09-08 11:03
Yes, in this endpoint we can return 200 in case of entity present or 204 in case of entity not present (so the call was ok but there is no content to display).
We tried to put the attribute writing that the endpoint will return a 204 and we saw that the cs file will have the checks for the 204 code even though the return from the API is OK (meaning 200). I'm trying to go on the details of that thing.

**Comment by jeremyVignelles** [comment] 2020-09-08 12:05
In my humble opinion, this is not the RESTful way of creating APIs.

Your API should return 404 when the entity is not found.

From a .net standpoint, I understand that this is easier for you to deal with a nullable on the client side, but I don't know how we handle the case properly in the client side, while respecting the nullability of the schema. (This is an issue that came after the proper implementation of nullable reference types).

**Comment by steppo83** [comment] 2020-09-08 12:54
You're right, in fact we're refactoring that endpoint since is not correct to return a 204, it's better to return a 404.

**Closed** 2020-09-15 13:16 UTC
Labels: state: done
