### ISSUE TITLE
Controller generation with custom CSharpTypeResolver

### ISSUE THREAD

**Issue by timmvonputtkamer** [RicoSuter/NSwag#2378] opened 2019-08-29 07:29 UTC
We currently use the NSwag.MSBuild package for generating C# controllers from our OpenAPI 3.0 spec. In some places in our spec we use custom formats which we like to translate to C# types that we defined. The CSharpTypeResolver of NJsonSchema seems to be the relevant piece. Is it possible to inject a custom class?

**Comment by RicoSuter** [comment] 2019-08-29 07:33
Duplicate of https://github.com/RicoSuter/NSwag/issues/924

Custom classes in the code generators are currently not supported. You need to build your own CLI based on the libraries

**Comment by MisinformedDNA** [comment] 2019-11-02 20:22
How would one go about creating a custom NSwag CLI? Any documentation out there?

**Comment by RicoSuter** [comment] 2019-11-04 15:18
You'd create an own console app and reference the NSwag code generation packages.

**Closed** 2023-09-28 06:59 UTC
Labels: duplicate
