### ISSUE TITLE
Respect LowercaseUrls

### ISSUE THREAD

**Issue by bangonkali** [RicoSuter/NSwag#1432] opened 2018-07-03 08:01 UTC
I added the following in my ConfigureServices section.

```
      services.AddRouting(options =>
      {
        options.LowercaseUrls = true;
      });
      services.AddSwagger();
```

```
 app.UseSwaggerUi3WithApiExplorer(settings =>
      {
        settings.GeneratorSettings.DefaultPropertyNameHandling = PropertyNameHandling.Default;
        settings.GeneratorSettings.OperationProcessors.Add(new OperationSecurityScopeProcessor("Authorization"));
        settings.GeneratorSettings.OperationProcessors.Add(new OperationSecurityScopeProcessor("ServiceAccount"));

        settings.GeneratorSettings.DocumentProcessors.Add(
          new SecurityDefinitionAppender("Authorization", new SwaggerSecurityScheme
          {
            Type = SwaggerSecuritySchemeType.ApiKey,
            Name = "Authorization",
            Description = "The identity token responsible for request.",
            In = SwaggerSecurityApiKeyLocation.Header
          }));

        settings.GeneratorSettings.DocumentProcessors.Add(
          new SecurityDefinitionAppender("ServiceAccount", new SwaggerSecurityScheme
          {
            Type = SwaggerSecuritySchemeType.ApiKey,
            Name = "ServiceAccount",
            Description = "The service account token responsible for request.",
            In = SwaggerSecurityApiKeyLocation.Header
          }));
      });
```

The capitalization is not being respected in the SwaggerUI.

Similar to https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/74 on Swashbuckle Implementation.

**Comment by RSuter** [comment] 2018-07-03 08:20
It seems that ASP.NET Core API Explorer does not take this into account. Either we implement this on our side, or it has to be fixed in ASP.NET Core API Explorer. @pranavkm Is this by design or a "bug" in ASP.NET Core?

I created a PR to reproduce this: https://github.com/RSuter/NSwag/pull/1433

And indeed the path has still upper case chars: 
![image](https://user-images.githubusercontent.com/2603405/42207603-9ad915cc-7eaa-11e8-9674-8b955ff12848.png)

**Comment by RSuter** [comment] 2018-07-03 08:21
For now, you could implement a document processor which lower cases all paths (except the route param placeholders!).

**Comment by bangonkali** [comment] 2018-07-03 12:07
Hi @RSuter , I made something like this but I don't think this one is heading in the right direction.

Could you provide some tips?

```
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using NSwag.SwaggerGeneration.Processors;
using NSwag.SwaggerGeneration.Processors.Contexts;

namespace Gapp.Api.Swagger.DocumentProcessors
{
  public class ForceLowerCaseRoutes : IDocumentProcessor
  {
    private readonly ILogger _logger;

    public ForceLowerCaseRoutes(ILogger logger)
    {
      _logger = logger;
    }

    public Task ProcessAsync(DocumentProcessorContext context)
    {
      var paths = context.Document.Paths.ToDictionary(path => LowerCasePathOnly(path.Key), path => path.Value);
      context.Document.Paths.Clear();
      foreach (var path in paths)
      {
        context.Document.Paths.Add(path);
      }
      return null;
    }

    private static string LowerCasePathOnly(string path)
    {
      StringBuilder result = new StringBuilder();
      bool inScope = false;
      
      foreach (var c in path)
      {
        char d = ' ';
        
        switch (c)
        {
          case '{':
            inScope = true;
            break;
          case '}':
            inScope = false;
            break;
        }

        d = !inScope ? char.ToLower(c) : c;

        result.Append(d);
      }
      return result.ToString();
    }
  }
}
```

![image](https://user-images.githubusercontent.com/539946/42218924-bb74ba5a-7efc-11e8-9392-37db6c5ad4ea.png)

**Comment by RSuter** [comment] 2018-07-03 12:10
You can directly call the swagger.json url to see an exception...

But I think it's your `return null;` in `ProcessAsync` - it has to return a task instance - use `return Task.CompletedTask;`

**Comment by bangonkali** [comment] 2018-07-03 12:12
Awesome!!!

To be honest I didn't have any clue about `Task.CompletedTask;`. I will do some testing. But so far this one works.

```
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NSwag.SwaggerGeneration.Processors;
using NSwag.SwaggerGeneration.Processors.Contexts;

namespace Gapp.Api.Swagger.DocumentProcessors
{
  public class ForceLowerCaseRoutes : IDocumentProcessor
  {
    public ForceLowerCaseRoutes()
    {
    }

    public Task ProcessAsync(DocumentProcessorContext context)
    {
      var paths = context.Document.Paths.ToDictionary(path => LowerCasePathOnly(path.Key), path => path.Value);
      context.Document.Paths.Clear();
      foreach (var path in paths)
      {
        context.Document.Paths.Add(path);
      }
      return Task.CompletedTask;
    }

    private static string LowerCasePathOnly(string path)
    {
      StringBuilder result = new StringBuilder();
      bool inScope = false;
      
      foreach (var c in path)
      {
        char d = ' ';
        
        switch (c)
        {
          case '{':
            inScope = true;
            break;
          case '}':
            inScope = false;
            break;
        }

        d = !inScope ? char.ToLower(c) : c;

        result.Append(d);
      }
      return result.ToString();
    }
  }
}
```

**Comment by RSuter** [comment] 2018-07-03 12:16
Good to hear, but I still think that this should be automatically handled by ASP.NET Core API Explorer or at least NSwag :)

**Comment by RSuter** [comment] 2018-07-03 12:17
BTW: Newer return null as Task, when someone awaits null you'll get a null pointer exception

**Comment by pranavkm** [comment] 2018-07-03 16:42
cc @rynowak \ @kichalla, do you know off hand if this is something we could handle in ApiExplorer i.e. have `LowercaseUrls` affect the value in `ApiDescription`. Is that property only considered during link generation?

**Comment by kichalla** [comment] 2018-07-03 16:54
> Is that property only considered during link generation?

Yes

> do you know off hand if this is something we could handle in ApiExplorer i.e. have LowercaseUrls affect the value in ApiDescription

No idea

**Comment by pranavkm** [comment] 2018-07-03 18:48
Filed https://github.com/aspnet/Mvc/issues/8006 to track addressing this in MVC.

**Comment by RSuter** [comment] 2018-07-04 11:04
Thanks for creating a new issue. 

@bangonkali it seems that this is currently not supported by ASP.NET Core API Explorer. I'd suggest to use your document processor for now... 

Maybe we can move this processor to the NSwag library so that everyone can use it (not registered by default)?

**Comment by bangonkali** [comment] 2018-07-06 04:43
@RSuter yep we can. I’d be glad to help. Just guide me if there’s anything I have to do.

**Comment by RSuter** [comment] 2018-08-03 13:40
This has been fixed in ASP.NET Core: https://github.com/aspnet/Mvc/issues/8006

Can we close this now?

**Comment by jsancho** [comment] 2018-08-15 10:28
The fix has been merged indeed by the ASP .NET Core team.
Nevertheless, one could argue that this issue should stay opened until it cannot be reproduced? i.e. ASP .NET Core 2.2 is released

**Comment by bangonkali** [comment] 2018-08-16 00:32
We will try to update our stack to 2.2 and will get back to this. Thanks guys!

**Comment by RSuter** [comment] 2018-08-16 06:35
Until v2.2 is released you can use the processor above..

**Comment by bangonkali** [comment] 2019-03-27 04:58
Currently using `services.AddRouting(options => { options.LowercaseUrls = true; });` on 2.2 but still the generated routes are `CamelCase`.

**Comment by bangonkali** [comment] 2019-03-27 05:02
Okay it turns out I was using 

```
opt.EnableEndpointRouting = false;
```

If this is false then it will not work. My First use of OData required me to use this but a [video](https://www.youtube.com/watch?v=ZCDWUBOJ5FU) from here shows it isn't needed so I've removed it since and the correct casing is now follows.

I think this can now be closed if `opt.EnableEndpointRouting = false;` is a known side effect.

**Closed** 2019-03-27 05:14 UTC
Labels: project: NSwag.AspNetCore, state: on-hold
