### ISSUE TITLE
NSwag.MSBuild NetCore 3.0

### ISSUE THREAD

**Issue by grahamehorner** [RicoSuter/NSwag#2407] opened 2019-09-16 12:55 UTC
Please advise if NSwag.MSBuild is supports .NET Core 3.0 if so we  have issues when using .NET Core 3.0 and NSwag.MSBuild in that the NSwag build task is throwing a System.IO.FileNotFoundException when running and referencing a build folder that is incorrect.

**Comment by RicoSuter** [comment] 2019-09-16 14:17
NSwag.MSBuild does not yet support .NET Core 3.0

**Comment by robertsundstrom** [comment] 2019-09-19 06:17
@ricosuter What is the ETA?

**Comment by robertsundstrom** [comment] 2019-09-23 16:57
I have looked into the .NET project NSwag service generator support:

```xml
  <ItemGroup>
    <OpenApiReference Include="OpenAPIs\swagger.json" Namespace="BlazorApp1">
      <CodeGenerator>NSwagCSharp</CodeGenerator>
      <SourceUri>http://localhost:58687/swagger/v1/swagger.json</SourceUri>
    </OpenApiReference>
  </ItemGroup>
```

Any documentation of what the options are?

My client gets the name `swaggerClient` and not the name of the controller, why?

**Comment by RicoSuter** [comment] 2019-09-23 17:23
The only docs so far: https://github.com/RicoSuter/NSwag/wiki/ServiceProjectReference

**Comment by mhartvig** [comment] 2019-09-23 19:38
Hi Rico,
Any chance you have time to address this? With the release of 3.0 today (https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0/), it would be nice to be able to upgrade asap.

**Comment by RicoSuter** [comment] 2019-09-23 19:39
Duplicate of https://github.com/RicoSuter/NSwag/issues/1961

**Comment by RicoSuter** [comment] 2019-09-23 19:40
I hope to look into this this week...

**Closed** 2019-09-26 18:56 UTC

**Comment by RicoSuter** [comment] 2019-09-26 19:43
https://github.com/RicoSuter/NSwag/pull/2427

**Comment by RicoSuter** [comment] 2019-09-26 21:12
Also supports NRT: 

![image](https://user-images.githubusercontent.com/2603405/65725507-21a8f700-e0b3-11e9-9a82-6cb139a12980.png)
