### ISSUE TITLE
Unexpected initial token 'String' when populating object

### ISSUE THREAD

**Issue by chfn** [RicoSuter/NSwag#2065] opened 2019-04-01 11:36 UTC
I get the following error when trying to generate .net core code from swagger specifications .yml

Newtonsoft.Json.JsonSerializationException: Unexpected initial token 'String' when populating object. Expected JSON object or array. Path 'paths['/api/acceptatie/scenario/foobar/v1'].__referencePath', line 1, position 592.

Runtime: NetCore21
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at NJsonSchema.ExtensionDataDeserializationConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at NSwag.SwaggerPathItem.SwaggerPathItemConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\projects\nswag\src\NSwag.Core\SwaggerPathItem.cs:line 89
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at NJsonSchema.ExtensionDataDeserializationConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NJsonSchema.Infrastructure.JsonSchemaSerialization.FromJsonAsync[T](String json, SchemaType schemaType, String documentPath, Func`2 referenceResolverFactory, IContractResolver contractResolver)
   at NSwag.SwaggerDocument.FromJsonAsync(String data, String documentPath, SchemaType expectedSchemaType, Func`2 referenceResolverFactory) in C:\projects\nswag\src\NSwag.Core\SwaggerDocument.cs:line 187
   at NSwag.SwaggerYamlDocument.FromYamlAsync(String data, String documentPath, SchemaType expectedSchemaType, Func`2 referenceResolverFactory) in C:\projects\nswag\src\NSwag.Core.Yaml\SwaggerYamlDocument.cs:line 70
   at NSwag.Commands.OutputCommandBase.ReadSwaggerDocumentAsync(String input) in C:\projects\nswag\src\NSwag.Commands\Commands\OutputCommandBase.cs:line 52
   at NSwag.Commands.SwaggerGeneration.FromSwaggerCommand.RunAsync() in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\FromSwaggerCommand.cs:line 62
   at NSwag.Commands.SwaggerGeneration.FromSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\FromSwaggerCommand.cs:line 53
   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 268
   at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 81
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 77
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 31
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 54

**Comment by RicoSuter** [comment] 2019-04-01 12:35
Can you provide a sample yaml spec?

**Comment by chfn** [comment] 2019-04-01 12:37
`swagger: '2.0'
info:
  description: This is a description
  version: '0.2'
  title: xxx-service rest API
host: 'localhost:6080'
basePath: /
paths:

  /api/acceptatie/scenario/foobar/v1:
    $ref: local/v1/scenario/foobar_v1.yml

definitions:
  $ref: inheritance_definitions.yml`

**Comment by RicoSuter** [comment] 2019-04-02 07:50
I think this is because currently externel files must be swagger specs too (here you have a file with a path item in the root)... if you’d reference into a swagger spec’s path item with spec.yaml#paths/... it should work

But we should support this

**Comment by RicoSuter** [comment] 2019-04-02 07:51
Probably a duplicate of
https://github.com/RicoSuter/NSwag/issues/1880

Pr: https://github.com/RicoSuter/NSwag/pull/1953

**Comment by chfn** [comment] 2019-04-02 08:12
refs doens't work indeed. I came across a tooling called **json-refs** it can resolve the yamls with refs into one big yaml. With that it works, but unfortunately it comes with a lot anonymous classes.

**Comment by Zoxive** [comment] 2019-04-18 17:34
I'm getting this error when i have no external files. My swagger document is also generated by NSwag, and I'm trying to generate a typescript client for it.

It does have ``"schema": {
"$ref": "#/definitions/FlattenedUIData"
}`` properties but all they are all defined inline.

**Comment by Zoxive** [comment] 2019-04-23 12:09
Turns out my issued was caused by a bug with dotnet core preview 3..
https://github.com/aspnet/AspNetCore/pull/8837

When i save my swagger.json file to a file first and use that it generates fine..

**Comment by flidr** [comment] 2019-08-19 14:05
I'm getting the same error on this trivial input.
```openapi: 3.0.1
info:
  title: Foo
  version: 1.0.0
paths:
  /something:
    description: operation description
    get:
      responses:
        200:
          description: get description
```
Once the description of `something` is removed then it works

**Comment by flidr** [comment] 2019-08-19 14:11
Another sample (anynimized real case). When `x-swagger-router-controller` removed then works.
Tried on version 12.3.1 and 13.0.5
```
swagger: '2.0'
info:
  title: foo
  version: '1.0'
paths:
  /bar:
    x-swagger-router-controller: bar
    get:
      responses:
        '200':
          description: baz
```

**Comment by alexmartinezm** [comment] 2019-10-08 10:53
This package becomes unusable due this bug...

**Closed** 2019-10-08 12:11 UTC
