### ISSUE TITLE
null values in querystring

### ISSUE THREAD

**Issue by Anderman** [RicoSuter/NSwag#2528] opened 2019-11-15 14:34 UTC
Nswag generated wrong querystring when using null values
example
http://localhost:4000/api/SurveyManagement/UpdateRouteSurvey?toSurveyId=null

expected
http://localhost:4000/api/SurveyManagement/UpdateRouteSurvey?toSurveyId=
or
http://localhost:4000/api/SurveyManagement/UpdateRouteSurvey

see https://stackoverflow.com/questions/58765126/null-values-in-querystring-with-nswag

**Comment by RicoSuter** [comment] 2020-04-07 13:26
Duplicate of: https://github.com/RicoSuter/NSwag/issues/2000

**Closed by RicoSuter** 2020-04-07 13:26 UTC
Labels: duplicate
