### ISSUE TITLE
Control line feed type via nswag.json?

### ISSUE THREAD

**Issue by xantari** [RicoSuter/NSwag#2503] opened 2019-11-03 19:09 UTC
It appears that when API Contracts and Clients are created with NSwag the line feeds are always LF's.

Our global Git settings conflict with this setting. (We convert everything to CRLF's).

Is it possible to control line feeds with nswag and the .cs code it generates?

**Comment by RicoSuter** [comment] 2019-11-04 15:01
Duplicate of https://github.com/RicoSuter/NSwag/issues/1133

**Closed** 2019-11-04 15:01 UTC
Labels: duplicate
