### ISSUE TITLE
Problem with null values in NSwagStudio v13.7

### ISSUE THREAD

**Issue by Chrille79** [RicoSuter/NSwag#3014] opened 2020-08-18 17:49 UTC
After upgrading NSwag studio to v13.7 the code changes to do a null check on the response 

``` 
if (status_ == 200)
 {
   var objectResponse_ = await ReadObjectResponseAsync<Agreement>(response_, headers_).ConfigureAwait(false);
   if (objectResponse_.Object == null)
   {
        throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
   }
 return objectResponse_.Object;
 }
```
This may as something to do with Nullable Reference Types. But we have not enabled NRT in our project yet and we expect to return null in some cases

Is there a flag to turn of the null check or do I have to use an older version of NSwagStudio?

**Comment by jeremyVignelles** [comment] 2020-08-18 17:51
I'm currently in the process of fixing issues related to this, see #2995 and linked issues.

Which asp.net core version are you running ?

Actually, it's a duplicate of #3005

**Comment by Chrille79** [comment] 2020-08-18 17:54
Im using 3.1

**Comment by Chrille79** [comment] 2020-08-18 17:59
I hope there is a better way than to decorate the action with [CanBeNullAttribute] because we have 833 actions

**Comment by jeremyVignelles** [comment] 2020-08-18 18:03
Embrace NullableReferenceTypes (can be enabled on the file only, by putting `#nullable enable` on top) and really check what can and what cannot be null ? That can be inferred from a nullable return type.

**Comment by RicoSuter** [comment] 2020-08-18 18:04
Probably you can set DefaultResponseReferenceTypeNullHandling to Null and change the default this way.

https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Generation/OpenApiDocumentGeneratorSettings.cs#L47

**Comment by Chrille79** [comment] 2020-08-18 18:06
We will embrace NRT, but not yet.. DefaultResponseReferenceTypeNullHandling see to be the way to go.
We try that

Tnx

**Comment by RicoSuter** [comment] 2020-08-18 18:21
Can you provide a sample operation method implementation which returns "null" as response and HTTP 200 (repro of your problem)?

**Comment by Chrille79** [comment] 2020-08-18 18:49
It works by setting DefaultResponseReferenceTypeNullHandling 
`services.AddOpenApiDocument(doc =>{ doc.DefaultResponseReferenceTypeNullHandling = NJsonSchema.Generation.ReferenceTypeNullHandling.Null; });`

But not with the default `services.AddOpenApiDocument();`

So this will fix our problem..

I made a quick project to verify

Startup
```
 public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers(options =>
            {
                options.OutputFormatters.RemoveType<HttpNoContentOutputFormatter>();
            }).AddNewtonsoftJson(options =>
            {
                options.SerializerSettings.Formatting = Formatting.Indented;
                options.SerializerSettings.PreserveReferencesHandling = PreserveReferencesHandling.None;
                options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
                options.SerializerSettings.Converters.Add(new StringEnumConverter());
                options.SerializerSettings.ContractResolver = new DefaultContractResolver();
                options.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;
            }).ConfigureApiBehaviorOptions(options =>
            {
                options.SuppressModelStateInvalidFilter = true;
            });

            //Works
            services.AddOpenApiDocument(doc =>{ doc.DefaultResponseReferenceTypeNullHandling = NJsonSchema.Generation.ReferenceTypeNullHandling.Null; });

            //Fail
            //services.AddOpenApiDocument();
        }
```
And my controller
```
 [ApiController]
    [Route("[controller]")]
    public class TestController : ControllerBase
    {
        private readonly ILogger<TestController> _logger;

        public TestController(ILogger<TestController> logger)
        {
            _logger = logger;
        }

        [HttpGet("[action]")]
        public IEnumerable<Person> GetAllPerson()
        {
            return null;
        }

        [HttpGet("[action]")]
        public IEnumerable<Person> GetEmptyListPerson()
        {
            return new List<Person>();
        }

        [HttpGet("[action]")]
        public IEnumerable<Person> Get()
        {
            return null;
        }
    }
```

**Closed** 2020-08-18 19:04 UTC

**Comment by Chrille79** [comment] 2020-08-18 19:11
Now own both the server and the client.. but it can be good if you can alter this behavior as a parameter in NSwagClient if there is an existing Api
