### ISSUE TITLE
Configure Typescript Client to accept all 2XX status codes?

### ISSUE THREAD

**Issue by SebastianStehle** [RicoSuter/NSwag#3545] opened 2021-07-07 07:41 UTC
Hi,

the API I am currently work with is a little big buggy. Sometimes you get a 201, but a 200er is documented and vice versa. Then the generated typescript client does not deserialize the results.

Can you configure the client generator to treat all 2XX status codes the same?

**Comment by jeremyVignelles** [comment] 2021-07-08 05:06
Duplicate of #1259, #2995 ...

**Closed by jeremyVignelles** 2021-07-08 05:06 UTC
