### ISSUE TITLE
Enum parameters do not appear in UI with OAPI 3.0

### ISSUE THREAD

**Issue by staingp** [RicoSuter/NSwag#2535] opened 2019-11-19 17:06 UTC
Enums don't appear in SwaggerUI when ` .AddOpenApiDocument()` is used (worked fine with `.AddSwaggerDocument()`).

This is the enums definition:

```
[JsonConverter(typeof(StringEnumConverter))]
    public enum LoginType
    {
        UserPassword = 0,
        Facebook = 1,
        Google = 2
    }
```
 ```
[JsonConverter(typeof(StringEnumConverter))]
    public enum UserType
    {
        Portale = 1,
        CU = 2,
        Mobile = 3
    }
```

The enums are correctly rendered in the model section.

Using .Net Core 2.2 and NSwag.AspNetCore 13.1.5

**Comment by staingp** [comment] 2019-11-22 09:02
Importing the swagger,json file into Postman the enum parametres are present; seems only a UI related issue...

**Comment by RicoSuter** [comment] 2019-11-22 11:08
Can you post the generated Swagger spec (or the part with the enums)

**Comment by staingp** [comment] 2019-11-22 11:42
This is the excerpt of the swagger.json generated using `.AddSwaggerDocument()`:
```
"/api/v1/Auth/mobile/authenticate": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Autentica l'utente sul sistema",
        "operationId": "Auth_MobileAuthenticate",
        "consumes": [
          "application/json-patch+json",
          "application/json",
          "text/json",
          "application/*+json"
        ],
        "produces": [
          "text/plain",
          "application/json",
          "text/json"
        ],
        "parameters": [
          {
            "name": "userInput",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserMobileInput"
            },
            "x-nullable": false
          }
        ],
        "responses": {
          "200": {
            "x-nullable": false,
            "description": "JWT token",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "x-nullable": false,
            "description": "",
            "schema": {
              "$ref": "#/definitions/ProblemDetails"
            }
          },
          "default": {
            "x-nullable": false,
            "description": "",
            "schema": {
              "$ref": "#/definitions/ProblemDetails"
            }
          }
        }
      }
    }
	"UserMobileInput": {
      "type": "object",
      "required": [
        "loginType",
        "tipoUtente"
      ],
      "properties": {
        "eMail": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "socialId": {
          "type": "string"
        },
        "nominativo": {
          "type": "string"
        },
        "loginType": {
          "minLength": 1,
          "allOf": [
            {
              "$ref": "#/definitions/LoginType"
            }
          ]
        },
        "tipoUtente": {
          "minLength": 1,
          "allOf": [
            {
              "$ref": "#/definitions/UserType"
            }
          ]
        }
      }
    },
    "LoginType": {
      "type": "string",
      "description": "",
      "x-enumNames": [
        "UserPassword",
        "Facebook",
        "Google"
      ],
      "enum": [
        "UserPassword",
        "Facebook",
        "Google"
      ]
    },
	 "UserType": {
      "type": "string",
      "description": "",
      "x-enumNames": [
        "Portale",
        "CU",
        "Mobile"
      ],
      "enum": [
        "Portale",
        "CU",
        "Mobile"
      ]
    }
```

with this result:
![image](https://user-images.githubusercontent.com/55922803/69423062-81272a00-0d25-11ea-8acc-4e764149681a.png)


...and this using `.AddOpenApiDocument()`

```
 "/api/v1/Auth/mobile/authenticate": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Autentica l'utente sul sistema",
        "operationId": "Auth_MobileAuthenticate",
        "requestBody": {
          "x-name": "userInput",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserMobileInput"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "200": {
            "description": "JWT token",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "400": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "default": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          }
        }
      }
    },
	 "UserMobileInput": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "loginType",
          "tipoUtente"
        ],
        "properties": {
          "eMail": {
            "type": "string",
            "nullable": true
          },
          "password": {
            "type": "string",
            "nullable": true
          },
          "socialId": {
            "type": "string",
            "nullable": true
          },
          "nominativo": {
            "type": "string",
            "nullable": true
          },
          "loginType": {
            "minLength": 1,
            "oneOf": [
              {
                "$ref": "#/components/schemas/LoginType"
              }
            ]
          },
          "tipoUtente": {
            "minLength": 1,
            "oneOf": [
              {
                "$ref": "#/components/schemas/UserType"
              }
            ]
          }
        }
      },
      "LoginType": {
        "type": "string",
        "description": "",
        "x-enumNames": [
          "UserPassword",
          "Facebook",
          "Google"
        ],
        "enum": [
          "UserPassword",
          "Facebook",
          "Google"
        ]
      },
	    "UserType": {
        "type": "string",
        "description": "",
        "x-enumNames": [
          "Portale",
          "CU",
          "Mobile"
        ],
        "enum": [
          "Portale",
          "CU",
          "Mobile"
        ]
      },
```
with this result:

![image](https://user-images.githubusercontent.com/55922803/69422886-2a215500-0d25-11ea-8da5-6d462e3243e4.png)


Let me know if you need further infos...

**Comment by RicoSuter** [comment] 2019-11-22 11:50
It probably works if you remove the minLength property on UserMobileInput.loginType?

So it's a problem with this indirection:
![image](https://user-images.githubusercontent.com/2603405/69423559-b2ecc080-0d26-11ea-8bdd-91b14603ce58.png)

**Comment by staingp** [comment] 2019-11-22 12:29
Removing the `[Required]` attribute on` UserMobileInput.LoginType` works.
So, with 3.0 specification, "required" attribute is no longer supported  on enums or is it an issue?

Thank you for your support.

**Comment by RicoSuter** [comment] 2019-11-22 12:33
> Removing the [Required] attribute on UserMobileInput.LoginType works.

How does the spec look after the change?

> So, with 3.0 specification, "required" attribute is no longer supported on enums or is it an issue?

It is supported but maybe Swagger UI cannot handle the produced spec

**Comment by staingp** [comment] 2019-11-22 12:37
New spec:
```
 "UserMobileInput": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "eMail": {
            "type": "string",
            "nullable": true
          },
          "password": {
            "type": "string",
            "nullable": true
          },
          "socialId": {
            "type": "string",
            "nullable": true
          },
          "nominativo": {
            "type": "string",
            "nullable": true
          },
          "loginType": {
            "$ref": "#/components/schemas/LoginType"
          },
          "tipoUtente": {
            "$ref": "#/components/schemas/UserType"
          }
        }
      },
```

**Comment by RicoSuter** [comment] 2019-11-22 12:40
Yeah, the problem is that Swagger UI cannot handle the allOf indirection but is able to handle direct $refs... we need to create an issue in the Swagger UI repo. 

Did you check whether ReDoc works as expected? Just to be sure the the allOf spec is actually "valid"?

**Comment by staingp** [comment] 2019-11-22 13:09
ReDoc without Required:
![image](https://user-images.githubusercontent.com/55922803/69428429-7377a180-0d31-11ea-9b73-fcea72a2f213.png)

with Required:
![image](https://user-images.githubusercontent.com/55922803/69428451-812d2700-0d31-11ea-9b91-1be623dea603.png)

**Comment by RicoSuter** [comment] 2019-11-22 13:46
I'd consider this a bug in NSwag/NJsonSchema. 

**Current**

Enum property with required:

```
        "required": [
          "loginType"
        ],
        "properties": {
          "loginType": {
            "minLength": 1,
            "oneOf": [
              {
                "$ref": "#/components/schemas/LoginType"
              }
            ]
          },
```

String property with required:

```
        "required": [
          "firstName"
        ],
        "properties": {
          "loginType": {
            "minLength": 1,
            "oneOf": [
              {
                "$ref": "#/components/schemas/FirstName"
              }
            ]
          },
```

**Correct**

Enum property with required:

```
        "required": [
          "loginType"
        ],
        "properties": {
          "loginType": {
              $ref": "#/components/schemas/LoginType"
          },
```

**Because the enum is internally a string, we add minLength/oneOf but this does not make sense for enums so adding it to "required" would be enough and it would also fix the problem in the UI**

String property with required (already correct):

```
        "required": [
          "firstName"
        ],
        "properties": {
          "loginType": {
            "minLength": 1,
            "oneOf": [
              {
                "$ref": "#/components/schemas/FirstName"
              }
            ]
          },
```

**Comment by RicoSuter** [comment] 2019-11-22 13:47
This must be fixed in https://github.com/RicoSuter/NJsonSchema
I'll just check if we can easily fix it there.

**Closed** 2019-11-22 14:06 UTC

**Comment by RicoSuter** [comment] 2019-11-22 16:44
v13.1.6

**Comment by staingp** [comment] 2019-11-22 16:50
Thank you.
